#!/usr/bin/env bash
# docflow map — one compact, token-light index of the whole docs tree.
# Each line: relative/path — purpose (first H1). An agent reads this ONE file,
# knows the layout, and opens the exact doc it needs. No tree-scanning.
#
# Usage: docflow-map.sh [--stdout] [docs-root]   (default: docs)
#   default    → writes <root>/INDEX.md
#   --stdout   → prints the map instead, so callers (validate) can compare the
#                committed INDEX.md against freshly generated output without
#                duplicating this generator.

set -euo pipefail

TO_STDOUT="no"
ROOT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --stdout) TO_STDOUT="yes"; shift ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) ROOT="$1"; shift ;;
  esac
done
[ -n "$ROOT" ] || ROOT="docs"
[ -d "$ROOT" ] || { echo "no docs root: $ROOT" >&2; exit 1; }
OUT="$ROOT/INDEX.md"

# Entry point for a category: its README, else its lowest-sorting file. Printed
# in the header so a consumer that reads only the first lines of this map (the
# SessionStart hook truncates) still sees every category, not just the ones that
# sort early.
category_entry() {
  dir="$1"
  if [ -f "$ROOT/$dir/README.md" ]; then
    printf '%s/README.md' "$dir"
    return
  fi
  # a category split into sub-folders (plans/upcoming/, reviews/bugs/) keeps its
  # index one level down — better than pointing at whichever file sorts first
  nested="$(find "$ROOT/$dir" -mindepth 2 -maxdepth 2 -type f -name 'README.md' 2>/dev/null | LC_ALL=C sort | head -1)"
  if [ -n "$nested" ]; then
    printf '%s' "${nested#"$ROOT"/}"
    return
  fi
  found="$(find "$ROOT/$dir" -type f -name '*.md' ! -name 'INDEX.md' 2>/dev/null | LC_ALL=C sort | head -1)"
  [ -n "$found" ] && printf '%s' "${found#"$ROOT"/}"
}

render_map() {
  echo "# Docs map — $(basename "$ROOT")/"
  echo "<!-- AUTO-GENERATED by docflow-map.sh. Lines = path — purpose. Open the exact doc. -->"
  echo
  echo "## Categories"
  for category in product-spec specs decisions references plans reviews changelog; do
    [ -d "$ROOT/$category" ] || continue
    count="$(find "$ROOT/$category" -type f -name '*.md' 2>/dev/null | wc -l | tr -d ' ')"
    [ "$count" = "0" ] && continue
    entry="$(category_entry "$category")"
    printf '%s/ (%s) — start: %s\n' "$category" "$count" "${entry:-$category/}"
  done
  echo
  echo "## All docs"
  # files grouped by top folder, alpha; one line each
  find "$ROOT" -type f -name '*.md' ! -name 'INDEX.md' | LC_ALL=C sort | while IFS= read -r f; do
    rel="${f#"$ROOT"/}"
    desc="$(grep -m1 -E '^#[^#]' "$f" 2>/dev/null | sed -E 's/^#+[[:space:]]*//; s/<!--.*-->//')"
    [ -z "$desc" ] && desc="—"
    printf '%s — %s\n' "$rel" "$desc"
  done
}

if [ "$TO_STDOUT" = "yes" ]; then
  render_map
  exit 0
fi

render_map > "$OUT"

echo "docflow: wrote $OUT ($(grep -c ' — ' "$OUT") entries)"
